# Generated by Django 6.0.6 on 2026-07-08 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysis',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='analysis',
            name='ats_score',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='grammar_score',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
