# Generated by Django 6.0.6 on 2026-07-09 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobdescription',
            options={'ordering': ['-created_at'], 'verbose_name': 'Job Description', 'verbose_name_plural': 'Job Descriptions'},
        ),
        migrations.DeleteModel(
            name='JobMatchAnalysis',
        ),
    ]
