# Generated by Django 6.0.6 on 2026-07-10 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_alter_resume_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='public_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
