# Generated by Django 6.0.6 on 2026-07-10 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0003_resume_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='public_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
